name: Create GitHub release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    if: github.repository == 'chicory-pizza/chicory-macaroni'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip for GitHub release
        run: |
          zip -rj "Chicory_Macaroni.zip" macaroni/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          # spaces in file names change to dots on upload :(
          files: |
            Chicory_Macaroni.zip
